[package]
name = "view"
version = "0.1.0"
authors = ["Tomasz Stachowiak <h3@h3.gd>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kajiya = { path = "../../lib/kajiya" }
kajiya-simple = { path = "../../lib/kajiya-simple", features = ["dear-imgui"] }

anyhow = "1.0"
futures = "0.3"
glam = { version = "0.12", features = ["serde"] }
imgui = "0.7"
lazy_static = "1.4"
log = "0.4"
parking_lot = "0.11"
ron = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
smol = "1.2.5"
structopt = "0.3"
turbosloth = { git = "https://github.com/h3r2tic/turbosloth.git", rev = "92030af" }
winit = "0.24"
