[package]
name = "bake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kajiya-asset = { path = "../../lib/kajiya-asset" }
kajiya-asset-pipe = { path = "../../lib/kajiya-asset-pipe" }

env_logger = "0.8.4"
anyhow = "1.0"
structopt = "0.3"
