[package]
name = "bake"
version = "0.1.0"
authors = ["Tomasz Stachowiak <h3@h3.gd>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kajiya-asset = { path = "../../lib/kajiya-asset" }
kajiya-backend = { path = "../../lib/kajiya-backend" }

anyhow = "1.0"
async-channel = "1.6"
async-executor = "1.4"
easy-parallel = "3.1"
futures = "0.3"
glam = "0.17"
num_cpus = "1.13"
smol = "1.2.5"
structopt = "0.3"
turbosloth = { git = "https://github.com/h3r2tic/turbosloth.git", rev = "92030af" }